### ISSUE TITLE
关于lora finetuning

### ISSUE THREAD

**Issue by guihonghao** [OpenNLG/OpenBA#5]
你好，想请教您几个问题：
1、如果我想使用OpenBA做信息抽取任务，我应该在OpenBA-LM还是OpenBA-Flan上进行微调？
2、在lora微调的时候，指令是否需要像alpaca template一样使用这种格式？
Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:\n
还是说直接用query = "<S>" + instruction + "<extra_id_0>"这种格式？

**Comment by ZetangForward** [comment]
Hello, thank you for your interest in OpenBA. The effectiveness of using OpenBA depends on the size of your data and the purpose of using this model.

For instance, if you have sufficient data, with over 100,000 instances, and want to apply OpenBA for a specific task, such as IE, you can fine-tune OpenBA-LM directly. You can also customize the prompt according to your needs instead of using the given ``alpaca template``, which is designed for multi-task learning.

However, if you have limited data and are developing a toy model for a quick experiment, it's advisable to continue training based on the OpenBA-Flan version. You should apply a similar prompt as the one provided in the report to prevent model collapse.

**Comment by guihonghao** [comment]
请问是否有现成的lora tuning openba的代码？

**Comment by ZetangForward** [comment]
> 请问是否有现成的lora tuning openba的代码？

We haven't released this code, but you can follow the Lora tuning code from T5 model in HF.
